* [32m(HEAD detached at d71615f)[m
  db[m
  master[m
  prod[m
  staticfiles[m
  [31mremotes/origin/F-request-form[m
  [31mremotes/origin/F-request-page[m
  [31mremotes/origin/Frontend[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/actions-in-informationList[m
  [31mremotes/origin/actions-in-requestPage[m
  [31mremotes/origin/add-icons-in-request-page[m
  [31mremotes/origin/add-spaces[m
  [31mremotes/origin/add-thanks-page[m
  [31mremotes/origin/admin-custom[m
  [31mremotes/origin/api-coverage[m
  [31mremotes/origin/back-branch-v1[m
  [31mremotes/origin/back-branch-v2[m
  [31mremotes/origin/back-v4[m
  [31mremotes/origin/back-v5[m
  [31mremotes/origin/back-v6[m
  [31mremotes/origin/backend[m
  [31mremotes/origin/backend-api[m
  [31mremotes/origin/backend-coverage[m
  [31mremotes/origin/backend-v3[m
  [31mremotes/origin/build[m
  [31mremotes/origin/change-router-icon[m
  [31mremotes/origin/city-and-houses[m
  [31mremotes/origin/coverage[m
  [31mremotes/origin/coverage-2[m
  [31mremotes/origin/coverage-fix-2[m
  [31mremotes/origin/coverage-fix-3[m
  [31mremotes/origin/css-media[m
  [31mremotes/origin/db[m
  [31mremotes/origin/design-fix[m
  [31mremotes/origin/dev-branch-1[m
  [31mremotes/origin/dev-branch-2[m
  [31mremotes/origin/finish[m
  [31mremotes/origin/fix[m
  [31mremotes/origin/fix-background[m
  [31mremotes/origin/fix-endpoints[m
  [31mremotes/origin/fix-icons-in-request-page[m
  [31mremotes/origin/fix-imgs[m
  [31mremotes/origin/fix-input-phone[m
  [31mremotes/origin/fix-inputs[m
  [31mremotes/origin/fix-modal[m
  [31mremotes/origin/fix-modal2[m
  [31mremotes/origin/fix-providers-image-in-address-form[m
  [31mremotes/origin/fix-reload-home-page[m
  [31mremotes/origin/fix-request-page[m
  [31mremotes/origin/fix-request2[m
  [31mremotes/origin/fix-requests[m
  [31mremotes/origin/fix-suggestions-list[m
  [31mremotes/origin/fix-thankyou-page[m
  [31mremotes/origin/fix-translate[m
  [31mremotes/origin/fix4[m
  [31mremotes/origin/fix6[m
  [31mremotes/origin/form-page[m
  [31mremotes/origin/front[m
  [31mremotes/origin/google-search-console[m
  [31mremotes/origin/houses[m
  [31mremotes/origin/houses-fix[m
  [31mremotes/origin/houses-new[m
  [31mremotes/origin/language[m
  [31mremotes/origin/little-fix[m
  [31mremotes/origin/loader[m
  [31mremotes/origin/master[m
  [31mremotes/origin/modal-after-30-second[m
  [31mremotes/origin/modal-window[m
  [31mremotes/origin/modal-with-not-found[m
  [31mremotes/origin/new-api[m
  [31mremotes/origin/new-total-coverage[m
  [31mremotes/origin/newTest[m
  [31mremotes/origin/news-added[m
  [31mremotes/origin/offers[m
  [31mremotes/origin/prod[m
  [31mremotes/origin/provider-update-v1[m
  [31mremotes/origin/quick-fix[m
  [31mremotes/origin/request-form[m
  [31mremotes/origin/router-icon-in-betteroffercard[m
  [31mremotes/origin/sarkor[m
  [31mremotes/origin/search-by-house[m
  [31mremotes/origin/speedtest[m
  [31mremotes/origin/test[m
  [31mremotes/origin/test2[m
  [31mremotes/origin/urls-fix[m
  [31mremotes/origin/urls-path-fix[m
  [31mremotes/origin/validation[m
