# Generated by Django 4.1.6 on 2023-03-07 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150, verbose_name='district')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('houses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Coverage',
                'verbose_name_plural': 'Coverage',
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(max_length=100, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='speed',
            field=models.CharField(max_length=100, verbose_name='speed'),
        ),
    ]
