# Generated by Django 4.1.7 on 2023-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150, verbose_name='district')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('houses', models.TextField(max_length=1000, verbose_name='houses')),
            ],
            options={
                'verbose_name': 'Coverage',
                'verbose_name_plural': 'Coverages',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='title')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('speed', models.CharField(max_length=100, verbose_name='speed')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
