# Generated by Django 4.1.6 on 2023-03-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('info', models.TextField(blank=True, verbose_name='info')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('house', models.CharField(max_length=100, verbose_name='house')),
            ],
            options={
                'verbose_name': 'Callback',
                'verbose_name_plural': 'Callbacks',
            },
        ),
        migrations.CreateModel(
            name='Coverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=150, verbose_name='district')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('providers', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Coverage',
                'verbose_name_plural': 'Coverages',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='provider')),
                ('name', models.CharField(max_length=100, verbose_name='title')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('speed', models.CharField(max_length=100, verbose_name='speed')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('tech', models.CharField(default='GPON', max_length=50, verbose_name='tech')),
                ('limit', models.CharField(blank=True, default='unlim', max_length=100, verbose_name='limit')),
                ('day', models.CharField(default='0', max_length=50, verbose_name='day')),
                ('night', models.CharField(default='0', max_length=50, verbose_name='night')),
                ('info', models.TextField(blank=True, verbose_name='info')),
                ('abonents', models.CharField(default='physic', max_length=100, verbose_name='abonents')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='TopProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='providers/images', verbose_name='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.allproviders', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'TopProviders',
                'verbose_name_plural': 'TopProviders',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='offer name')),
                ('plans', models.ManyToManyField(to='data.plan', verbose_name='Offers')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
