# Generated by Django 4.1.7 on 2023-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='provider',
            field=models.CharField(default='freelink', max_length=100, verbose_name='provider'),
            preserve_default=False,
        ),
    ]
