# Generated by Django 4.1.6 on 2023-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverages',
            name='providers',
            field=models.TextField(max_length=50, verbose_name='providers'),
        ),
    ]
