# Generated by Django 4.1.7 on 2023-03-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_plan_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Callback',
                'verbose_name_plural': 'Callbacks',
            },
        ),
    ]
