# Generated by Django 4.1.6 on 2023-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_coverages_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='status',
            field=models.CharField(default='opened', max_length=100, verbose_name='status'),
        ),
    ]
