# Generated by Django 4.1.6 on 2023-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_callback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('close', 'Closed')], default='opened', max_length=100, verbose_name='status'),
        ),
    ]
