# Generated by Django 4.1.6 on 2023-03-15 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_callback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user-id')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('logged', models.DateTimeField(auto_now_add=True, verbose_name='logged')),
            ],
            options={
                'verbose_name': 'BotUsers',
                'verbose_name_plural': 'BotUserss',
            },
        ),
        migrations.AddField(
            model_name='callback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
