# Generated by Django 4.1.6 on 2023-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_botusers_callback_created_plan_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'get_latest_by': 'created', 'verbose_name': 'Callback', 'verbose_name_plural': 'Callbacks'},
        ),
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='providers',
            field=models.TextField(max_length=200, verbose_name='providers'),
        ),
    ]
