# Generated by Django 4.1.6 on 2023-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_callback_options_alter_callback_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverages',
            name='providers',
        ),
        migrations.AddField(
            model_name='coverages',
            name='providers',
            field=models.ManyToManyField(to='data.allproviders', verbose_name='providers'),
        ),
    ]
