# Generated by Django 4.1.7 on 2023-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_plan_offer_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(default='temp', max_length=100, verbose_name='offer name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='plans',
            field=models.ManyToManyField(to='data.plan', verbose_name='Offers'),
        ),
    ]
