# Generated by Django 3.2.18 on 2023-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_coverages_providers_coverages_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='plans',
            field=models.ManyToManyField(max_length=3, to='data.Plan', verbose_name='Offers'),
        ),
    ]
