# Generated by Django 4.1.6 on 2023-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_coverages_providers_coverages_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='plan_id',
            field=models.IntegerField(default=1, verbose_name='plan_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='plans',
            field=models.ManyToManyField(max_length=3, to='data.plan', verbose_name='Offers'),
        ),
    ]
