# Generated by Django 4.1.6 on 2023-03-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_callback_plan_id_alter_offer_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproviders',
            options={'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterModelOptions(
            name='botusers',
            options={'verbose_name': 'Пользователь Бота', 'verbose_name_plural': 'Пользователи Бота'},
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'get_latest_by': 'created', 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='coverages',
            options={'verbose_name': 'Покрытие', 'verbose_name_plural': 'Покрытие'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Выгодное предложение', 'verbose_name_plural': 'Выгодные предложения'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='topproviders',
            options={'verbose_name': 'Топ провайдер', 'verbose_name_plural': 'Топ провайдеры'},
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='info',
            field=models.TextField(blank=True, verbose_name='Инфо'),
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='city',
            field=models.CharField(max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='district',
            field=models.CharField(max_length=100, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='house',
            field=models.CharField(max_length=100, verbose_name='дом'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.plan', verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=100, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='street',
            field=models.CharField(max_length=100, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='district',
            field=models.CharField(max_length=150, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='providers',
            field=models.ManyToManyField(to='data.allproviders', verbose_name='провайдеры'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='street',
            field=models.CharField(max_length=150, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название предложения'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='plans',
            field=models.ManyToManyField(max_length=3, to='data.plan', verbose_name='тарифы'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='abonents',
            field=models.CharField(default='physic', max_length=100, verbose_name='абоненты'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='day',
            field=models.CharField(default='0', max_length=50, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='info',
            field=models.TextField(blank=True, verbose_name='инфо'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit',
            field=models.CharField(blank=True, default='unlim', max_length=100, verbose_name='лимит'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='линейка'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='night',
            field=models.CharField(default='0', max_length=50, verbose_name='ночь'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(max_length=100, verbose_name='прайс'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='провайдер'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='speed',
            field=models.CharField(max_length=100, verbose_name='скорость'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tech',
            field=models.CharField(default='GPON', max_length=50, verbose_name='тех'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='topproviders',
            name='logo',
            field=models.ImageField(upload_to='providers/images', verbose_name='лого'),
        ),
        migrations.AlterField(
            model_name='topproviders',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.allproviders', verbose_name='провайдер'),
        ),
    ]
