# Generated by Django 4.1.6 on 2023-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_news_alter_topproviders_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
    ]
