# Generated by Django 4.1.6 on 2023-03-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_news_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='status',
            new_name='published',
        ),
    ]
