# Generated by Django 4.1.6 on 2023-04-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_rename_status_news_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.allproviders', verbose_name='провайдер'),
        ),
    ]
