# Generated by Django 4.1.6 on 2023-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_plan_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproviders',
            name='picture',
            field=models.ImageField(default='', upload_to='providers', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
