# Generated by Django 4.1.6 on 2023-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_allproviders_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproviders',
            name='logo',
        ),
    ]
