# Generated by Django 4.1.6 on 2023-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_topproviders_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproviders',
            name='text',
            field=models.TextField(default='', verbose_name='инфо'),
            preserve_default=False,
        ),
    ]
