# Generated by Django 4.1.6 on 2023-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_topproviders_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Выгодный'),
        ),
    ]
