# Generated by Django 4.1.6 on 2023-04-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_plan_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='houses',
            field=models.TextField(default='', verbose_name='дома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='picture',
            field=models.ImageField(upload_to='images', verbose_name='Картинка'),
        ),
    ]
