# Generated by Django 4.1.6 on 2023-04-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_allproviders_created_offer_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='картинка 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='картинка 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='картинка 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='', max_length=150, verbose_name='подзаголовок'),
            preserve_default=False,
        ),
    ]
