# Generated by Django 4.1.6 on 2023-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_news_image1_news_image2_news_image3_news_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='text1',
            field=models.TextField(default='', verbose_name='текст 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text2',
            field=models.TextField(blank=True, verbose_name='текст 2'),
        ),
    ]
