# Generated by Django 4.1.6 on 2023-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_news_text_news_text1_news_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproviders',
            name='best_plans',
            field=models.ManyToManyField(blank=True, to='data.plan', verbose_name='Лучшие тарифы'),
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='picture',
            field=models.ImageField(upload_to='images/provider', verbose_name='Картинка'),
        ),
    ]
