# Generated by Django 3.2.18 on 2023-04-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_offer_plans'),
        ('data', '0021_remove_news_text_news_text1_news_text2'),
    ]

    operations = [
    ]
