# Generated by Django 4.1.6 on 2023-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_allproviders_best_plans_alter_allproviders_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('providers', models.JSONField(default=list)),
                ('houses', models.JSONField(default=list)),
            ],
        ),
    ]
