# Generated by Django 3.2.18 on 2023-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_merge_20230406_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproviders',
            name='logo',
            field=models.ImageField(default='', upload_to='images', verbose_name='лого'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='picture',
            field=models.ImageField(upload_to='images/provider', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='plans',
            field=models.ManyToManyField(max_length=3, to='data.Plan', verbose_name='тарифы'),
        ),
    ]
