# Generated by Django 4.1.6 on 2023-04-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_testcoverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCoverage',
        ),
    ]
