# Generated by Django 4.1.6 on 2023-04-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_delete_testcoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='город'),
            preserve_default=False,
        ),
    ]
