# Generated by Django 4.1.6 on 2023-04-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_coverages_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverages',
            name='houses',
            field=models.JSONField(verbose_name='дома'),
        ),
    ]
