# Generated by Django 4.1.6 on 2023-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_coverages_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproviders',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
