# Generated by Django 3.2.18 on 2023-04-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_topproviders_logo'),
        ('data', '0026_alter_coverages_houses'),
    ]

    operations = [
    ]
