# Generated by Django 4.1.6 on 2023-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_allproviders_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='router',
            field=models.BooleanField(default=False, verbose_name='Есть роутер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topproviders',
            name='text',
            field=models.TextField(blank=True, verbose_name='инфо'),
        ),
    ]
