# Generated by Django 3.2.18 on 2023-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_allproviders_is_published'),
        ('data', '0027_merge_20230412_1623'),
    ]

    operations = [
    ]
