# Generated by Django 3.2.18 on 2023-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_merge_20230414_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topproviders',
            name='text',
            field=models.TextField(blank=True, verbose_name='инфо'),
        ),
    ]
