# Generated by Django 4.1.6 on 2023-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_plan_router_alter_topproviders_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='user-id'),
        ),
    ]
