# Generated by Django 3.2.18 on 2023-04-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_alter_botusers_user_id'),
        ('data', '0029_alter_topproviders_text'),
    ]

    operations = [
    ]
