# Generated by Django 4.1.6 on 2023-05-03 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_merge_20230424_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverages',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='изменен'),
        ),
    ]
