# Generated by Django 4.1.6 on 2023-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_coverages_created_coverages_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='ars_inform_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с арс инфор'),
        ),
        migrations.AddField(
            model_name='coverages',
            name='comnet_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с комнетом'),
        ),
        migrations.AddField(
            model_name='coverages',
            name='freelink_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с фрилинком'),
        ),
        migrations.AddField(
            model_name='coverages',
            name='sarkor_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с саркором'),
        ),
        migrations.AddField(
            model_name='coverages',
            name='uzonline_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с узонлайном'),
        ),
    ]
