# Generated by Django 4.1.6 on 2023-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_coverages_ars_inform_houses_coverages_comnet_houses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='city_net_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с ситинетом'),
        ),
    ]
