# Generated by Django 4.1.6 on 2023-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_coverages_city_net_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='gals_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с галс'),
        ),
        migrations.AddField(
            model_name='coverages',
            name='spectr_houses',
            field=models.JSONField(blank=True, default=list, verbose_name='дома с спектр'),
        ),
    ]
