# Generated by Django 4.1.6 on 2023-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_coverages_gals_houses_coverages_spectr_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='test_houses',
            field=models.TextField(blank=True, default='', verbose_name='тестовые дома'),
        ),
    ]
