# Generated by Django 4.1.6 on 2023-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_coverages_test_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverages',
            name='ars_inform_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с арс инфор'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='city_net_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с ситинетом'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='comnet_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с комнетом'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='freelink_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с фрилинком'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='gals_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с галс'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='sarkor_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с саркором'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='spectr_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с спектр'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='uzonline_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с узонлайном'),
        ),
    ]
