# Generated by Django 4.1.6 on 2023-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_coverages_ars_inform_houses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tasix',
            field=models.CharField(default='0', max_length=50, verbose_name='тасикс'),
        ),
    ]
