# Generated by Django 4.1.6 on 2023-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_plan_tasix'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='router_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инфо о роутере'),
        ),
    ]
