# Generated by Django 4.1.6 on 2023-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_plan_router_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverages',
            name='houses',
            field=models.TextField(blank=True, default='', verbose_name='дома'),
        ),
    ]
