# Generated by Django 4.1.6 on 2023-05-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_alter_coverages_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverages',
            name='test_houses',
        ),
    ]
