# Generated by Django 4.1.6 on 2023-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_remove_coverages_test_houses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverages',
            options={'ordering': ['district', 'street'], 'verbose_name': 'Покрытие', 'verbose_name_plural': 'Покрытие'},
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_speed_time',
            field=models.CharField(default='08:00-00:00', max_length=50, verbose_name='Скорость днем (Со сколько до скольки)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='nightly_speed_time',
            field=models.CharField(default='00:00-08:00', max_length=50, verbose_name='Скорость ночью (Со сколько до скольки)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='Есть ТВ'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tv_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инфо о ТВ'),
        ),
        migrations.AlterField(
            model_name='coverages',
            name='providers',
            field=models.ManyToManyField(blank=True, to='data.allproviders', verbose_name='провайдеры'),
        ),
    ]
