# Generated by Django 4.1.6 on 2023-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_alter_plan_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adressless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='номер')),
                ('status', models.CharField(default='opened', max_length=100, verbose_name='статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'Заявка без адреса',
                'verbose_name_plural': 'Заявки без адреса',
                'ordering': ['-created'],
            },
        ),
    ]
