# Generated by Django 4.1.6 on 2023-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_adressless'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['position', 'created'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='plan',
            name='position',
            field=models.CharField(default=20, max_length=100, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='adressless',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=100, verbose_name='статус'),
        ),
    ]
