# Generated by Django 4.1.6 on 2023-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_alter_plan_options_plan_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['position'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='plan',
            name='cabel_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Инфо о кабеле'),
        ),
        migrations.AddField(
            model_name='plan',
            name='more_info',
            field=models.TextField(blank=True, verbose_name='Доп инфо'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='position',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default=20, max_length=100, verbose_name='позиция'),
        ),
    ]
