# Generated by Django 4.1.6 on 2023-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_alter_plan_options_plan_cabel_text_plan_more_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cabel',
            field=models.BooleanField(default=False, verbose_name='Есть кабель'),
        ),
    ]
