# Generated by Django 4.1.6 on 2023-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_plan_cabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproviders',
            options={'ordering': ['position'], 'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AddField(
            model_name='allproviders',
            name='position',
            field=models.CharField(default='10', max_length=100, verbose_name='Позиция'),
        ),
    ]
