# Generated by Django 3.2.18 on 2023-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_alter_allproviders_options_allproviders_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproviders',
            name='position',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='10', max_length=100, verbose_name='Позиция'),
        ),
    ]
