# Generated by Django 4.1.6 on 2023-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_alter_allproviders_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adressless',
            options={'ordering': ['created'], 'verbose_name': 'Заявка без адреса', 'verbose_name_plural': 'Заявки без адреса'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='cabel_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Инфо о кабеле'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='router_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Инфо о роутере'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tv_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Инфо о ТВ'),
        ),
    ]
