# Generated by Django 4.1.6 on 2023-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_alter_adressless_options_alter_plan_cabel_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverages',
            name='optikom_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с оптиком'),
        ),
    ]
