# Generated by Django 4.1.6 on 2023-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_coverages_optikom_houses'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создвн')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Вопросы и ответы',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='cabel_text',
            field=models.TextField(blank=True, verbose_name='Инфо о кабеле'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='router_text',
            field=models.TextField(blank=True, verbose_name='Инфо о роутере'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tv_text',
            field=models.TextField(blank=True, verbose_name='Инфо о ТВ'),
        ),
    ]
