# Generated by Django 3.2.18 on 2023-08-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_questionandanswers_alter_plan_cabel_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionandanswers',
            options={'ordering': ['created'], 'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
    ]
