# Generated by Django 4.1.6 on 2023-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_questionandanswers_alter_plan_cabel_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('preferrable_time', models.CharField(max_length=100, verbose_name='Когда удобно говорить')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создвн')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок (С главной)',
            },
        ),
        migrations.AlterModelOptions(
            name='questionandanswers',
            options={'ordering': ['created'], 'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
    ]
