# Generated by Django 3.2.18 on 2023-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_alter_questionandanswers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('preferrable_time', models.CharField(max_length=100, verbose_name='Когда удобно говорить')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создвн')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
    ]
