# Generated by Django 4.1.6 on 2023-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_quickcallback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickcallback',
            options={'verbose_name': 'Заявка на обратный звонок', 'verbose_name_plural': 'Заявки на обратный звонок (С главной)'},
        ),
        migrations.AddField(
            model_name='coverages',
            name='sirius_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с сириус'),
        ),
    ]
