# Generated by Django 4.1.6 on 2024-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_alter_quickcallback_options_coverages_sirius_houses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproviders',
            options={'ordering': ['position', '-created'], 'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterField(
            model_name='allproviders',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
