# Generated by Django 4.1.6 on 2024-01-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_alter_allproviders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproviders',
            options={'ordering': ['-position', '-created'], 'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-provider__position', '-created'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='topproviders',
            options={'ordering': ['-provider__position', '-created'], 'verbose_name': 'Топ провайдер', 'verbose_name_plural': 'Топ провайдеры'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='position',
        ),
    ]
