# Generated by Django 4.1.6 on 2024-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_alter_allproviders_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip adress')),
                ('device', models.CharField(max_length=100, verbose_name='device')),
                ('click_time', models.DateTimeField(auto_now_add=True, verbose_name='click time')),
            ],
            options={
                'verbose_name': 'Клик (статистика)',
                'verbose_name_plural': 'Клики (статистика)',
            },
        ),
    ]
