# Generated by Django 4.1.6 on 2024-02-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_alter_clickevent_device_alter_clickevent_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='device',
            field=models.CharField(blank=True, default='none', max_length=100, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=50, verbose_name='ip adress'),
        ),
    ]
