# Generated by Django 3.2.18 on 2024-02-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_auto_20240207_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='device',
            field=models.CharField(blank=True, default='none', max_length=255, verbose_name='device'),
        ),
    ]
