# Generated by Django 4.1.6 on 2024-02-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_clickevent_title_alter_clickevent_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='device',
            field=models.CharField(blank=True, max_length=100, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='ip adress'),
        ),
    ]
