# Generated by Django 4.1.6 on 2024-04-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_auto_20240207_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='click_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время клика'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='device',
            field=models.CharField(blank=True, max_length=255, verbose_name='устройство'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='тип клика'),
        ),
    ]
