# Generated by Django 4.1.6 on 2024-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_alter_clickevent_click_time_alter_clickevent_device_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-provider__position', 'position', '-created'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='plan',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
    ]
