# Generated by Django 4.1.6 on 2024-04-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_alter_plan_options_plan_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-provider__position', '-position', '-created'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='coverages',
            name='nano_houses',
            field=models.TextField(blank=True, default='', verbose_name='дома с нано телеком'),
        ),
    ]
